---
title: "Running a national level single-country model"
output: 
  rmarkdown::html_vignette:
       toc: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Running a national level single-country model}
  %\usepackage[UTF-8]{inputenc}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load your library
```{r, include=TRUE, message=FALSE, eval=FALSE}
library(mcmsupply)
```


## Load the data 
```{r, include=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
cleaned_natdata <- get_data(national=TRUE, local=TRUE, mycountry="Nepal")
```


## Get the JAGS model inputs and the cleaned data
```{r, include=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
pkg_data <- get_modelinputs(startyear=1990, endyear=2025.5, nsegments=12, 
                            raw_data = cleaned_natdata)

```


## Run JAGS model and get posterior point estimates with uncertainty
```{r, include=TRUE, message=FALSE, eval=FALSE}
mod <- run_jags_model(jagsdata = pkg_data, jagsparams = NULL, 
                      n_iter = 50000, n_burnin = 10000, n_thin = 20)
```


## Plot posterior point estimates with uncertainty
```{r, include=TRUE, message=FALSE, eval=FALSE}
plots <- plot_estimates(jagsdata = pkg_data, model_output = mod) 
```
