---
output: html_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{How to run a national level model for multiple countries}
  %\usepackage[UTF-8]{inputenc}
---

### How to run a national level model for multiple countries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load your library

```{r, include=TRUE, message=FALSE}
library(mcmsupply)
library(dplyr)
```

### Load the data 

```{r, include=TRUE, message=FALSE, cache=TRUE}
cleaned_natdata <- get_data(national=TRUE)
```

### Get the JAGS model inputs and the cleaned data

```{r, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
pkg_data <- get_modelinputs(startyear=1990, endyear=2025.5, nsegments=12, raw_data = cleaned_natdata)

```

### Run JAGS model and get posterior point estimates with uncertainty

```{r, include=TRUE, message=FALSE, cache=TRUE}
mod <- run_jags_model(jagsdata = pkg_data, jagsparams = NULL, n_iter = 80000, n_burnin = 10000, n_thin = 35)
```

### Plot posterior point estimates with uncertainty

```{r, include=TRUE, message=FALSE, cache=TRUE}
plots <- plot_estimates(pkg_data) 
```
