---
title: "Running a subnational level single-country model"
output: 
  rmarkdown::html_vignette:
       toc: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Running a subnational level single-country model}
  %\usepackage[UTF-8]{inputenc}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load your library

```{r, include=TRUE, message=FALSE, eval=FALSE}
library(mcmsupply)
library(dplyr)
```


## Load the data 

```{r, include=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
cleaned_data <- get_data(national=FALSE, local=TRUE,
                         mycountry="Nepal")
```


## Get the JAGS model inputs and the cleaned data

```{r, include=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
pkg_data <- get_modelinputs(startyear=1990, endyear=2025.5,
                            nsegments=12, raw_data = cleaned_data)

```


## Run JAGS model and get posterior point estimates with uncertainty

```{r, include=TRUE, message=FALSE, eval=FALSE}
mod <- run_jags_model(jagsdata = pkg_data, jagsparams = NULL,
                      n_iter = 40000, n_burnin = 10000, n_thin = 15)
```


# Plot the traceplots of some parameters to assess their convergence 

```{r, include=TRUE, message=FALSE, eval=FALSE}
sample_draws <- tidybayes::tidy_draws(mod$BUGSoutput$sims.matrix)

var <- sample_draws %>% dplyr::select(.chain, .iteration, .draw,`P[1,2,1,1]`) %>%
  dplyr::mutate(chain = rep(1:2, each=2000)) %>%
  dplyr::mutate(iteration = rep(1:2000, 2))

ggplot2::ggplot(data=var) +
  ggplot2::geom_line(ggplot2::aes(x=iteration, y=`P[1,2,1,1]`, color=as.factor(chain)))
```


## Plot posterior point estimates with uncertainty

```{r, include=TRUE, message=FALSE, eval=FALSE}
plots <- plot_estimates(jagsdata = pkg_data, model_output = mod)
```


## Pull out estimates that you are particularly interested in

```{r, include=TRUE, message=FALSE, eval=FALSE}
estimates_2018 <- pull_estimates(model_output = mod, country = 'Nepal', year=2018)
```
