---
title: "How to run a subnational level model for multiple countries"
author: "Hannah Comiskey"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load your library

```{r, include=TRUE, message=FALSE}
library(mcmsupply)
library(dplyr)
```

## Get your data

```{r, include=TRUE, message=FALSE, eval=FALSE}
cleaned_subnatdata <- get_data(national=FALSE, local=FALSE, mycountry=NULL, fp2030=TRUE)
```

## Get the JAGS model inputs from the cleaned data


```{r, include=TRUE, message=FALSE, eval=FALSE}
pkg_data <- get_modelinputs(startyear=1990, endyear=2025.5, nsegments=12, raw_data = cleaned_subnatdata)
```

## Run JAGS model

```{r message=FALSE, eval=FALSE}
run_jags_model(jagsdata = pkg_data, jagsparams = NULL, main_path = "results/subnational/global/", n_iter = 80000, n_burnin = 10000, n_thin = 35)

```

## Get posterior point estimates

```{r, message=FALSE, eval=FALSE}
get_point_estimates(main_path="results/subnational/global/", pkg_data)
```


## Plot posterior point estimates with uncertainty

```{r, include=TRUE, message=FALSE, eval=FALSE}
plot_estimates(main_path="results/subnational/global/", vis_path="visualisation/subnational/global/", pkg_data) 
```
