---
title: "How to run a national level model for a multiple countries"
author: "Hannah Comiskey"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load your library

```{r, include=TRUE, message=FALSE}
library(mcmsupply)
library(dplyr)
```

## Load the data 

```{r, include=TRUE, message=FALSE, eval=FALSE}
cleaned_natdata <- get_data(national=TRUE, local=FALSE, mycountry=NULL, fp2030=TRUE)
```

## Get the JAGS model inputs and the cleaned data

```{r, include=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
pkg_data <- get_modelinputs(national=TRUE, local=FALSE, mycountry=NULL, startyear=1990, endyear=2025.5, nsegments=12, raw_data = cleaned_natdata)

```

## Run JAGS model

```{r, include=TRUE, message=FALSE, eval=FALSE}
run_jags_model(national=TRUE, jagsdata = pkg_data, jagsparams = NULL, local=FALSE, main_path = "results/national/", n_iter = 80000, n_burnin = 10000, n_thin = 35, mycountry=NULL)
```

## Get posterior point estimates

```{r, include=TRUE, message=FALSE, eval=FALSE}
get_point_estimates(national=TRUE, main_path="results/national/", pkg_data, local=FALSE, mycountry=NULL)
```

## Plot posterior point estimates

```{r, include=TRUE, message=FALSE, eval=FALSE}
plot_point_estimates(national=TRUE, main_path="results/national/", vis_path="visualisation/national/global/", pkg_data, local=FALSE, mycountry=NULL) 
```
