---
output: html_document
---

### How to run a national level model for multiple countries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load your library

```{r, include=TRUE, message=FALSE}
library(mcmsupply)
library(dplyr)
```

### Load the data 

```{r, include=TRUE, message=FALSE, eval=FALSE}
cleaned_natdata <- get_data(national=TRUE, local=FALSE, mycountry=NULL, fp2030=TRUE)
```

### Get the JAGS model inputs and the cleaned data

```{r, include=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
pkg_data <- get_modelinputs(startyear=1990, endyear=2025.5, nsegments=12, raw_data = cleaned_natdata)

```

### Run JAGS model and get posterior point estimates with uncertainty

```{r, include=TRUE, message=FALSE, eval=FALSE}
run_jags_model(jagsdata = pkg_data, jagsparams = NULL, main_path = "results/national/", n_iter = 80000, n_burnin = 10000, n_thin = 35)
```

### Plot posterior point estimates with uncertainty

```{r, include=TRUE, message=FALSE, eval=FALSE}
plot_estimates(main_path="results/national/", vis_path="visualisation/national/global/", pkg_data) 
```
