---
title: "How to run a local subnational model with a spatial component"
author: "Hannah Comiskey"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load your library

```{r, include=TRUE, message=FALSE}
library(mcmsupply)
library(dplyr)
```

```{r, include=FALSE}
devtools::load_all()
```

## Get your data

```{r, include=TRUE, message=FALSE}
raw_subnatdata <- mcmsupply::get_subnational_data(local=TRUE, mycountry="Nepal") %>%
  dplyr::arrange(Country, Region, Method, average_year)
```

## Get the JAGS model inputs and the cleaned data

```{r, include=TRUE, message=FALSE, warning=FALSE}
pkg_data <- mcmsupply::get_subnational_modelinputs(fp2030=TRUE, local=TRUE,
                                                          spatial=TRUE, mycountry="Nepal",
                                                          startyear=1990, endyear=2028.5,
                                                          nsegments=12, raw_subnatdata)

```

## Run JAGS model

```{r message=FALSE, eval=FALSE}
mod_global <- run_subnational_jags_model(pkg_data = pkg_data, local=TRUE, spatial=TRUE, main_path = "results/local_spatial/", n_iter = 80000, n_burnin = 10000, n_thin = 35, mycountry="Nepal")

```

## Get posterior point estimates

```{r, message=FALSE, eval=FALSE}
get_subnational_P_point_estimates(main_path = "results/subnational/local_spatial/", pkg_data, local=TRUE, spatial=TRUE, mycountry="Nepal")
```


## Plot posterior point estimates

```{r, include=TRUE, message=FALSE, eval=FALSE}
plot_subnational_point_estimates(main_path = "results/subnational/local_spatial/", pkg_data = pkg_data, vis_path = "visualisation/subnational/local_spatial/", local=TRUE, mycountry="Nepal")
```
