---
title: "How to run a global subnational model without a spatial component"
author: "Hannah Comiskey"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load your library

```{r, include=TRUE, message=FALSE}
library(mcmsupply)
library(dplyr)
```

## Get your data

```{r, include=TRUE, message=FALSE}
raw_subnatdata <- mcmsupply::get_subnational_data(local=FALSE, mycountry=NULL) 
```

## Get the JAGS model inputs from the cleaned data


```{r, include=TRUE, message=FALSE}
pkg_data <- mcmsupply::get_subnational_modelinputs(fp2030=TRUE, local=FALSE,
                                                          spatial=FALSE, mycountry=NULL,
                                                          startyear=1990, endyear=2028.5,
                                                          nsegments=12, raw_subnatdata)

```

## Run JAGS model

```{r message=FALSE, eval=FALSE}
mod_global <- run_subnational_jags_model(pkg_data = pkg_data, local=FALSE, spatial=FALSE, main_path = "results/global_nonspatial/", n_iter = 80000, n_burnin = 10000, n_thin = 35, mycountry=NULL)

```

## Get posterior point estimates

```{r, message=FALSE, eval=FALSE}
get_subnational_P_point_estimates(main_path = "results/subnational/global_nonspatial/", pkg_data, local=FALSE, spatial=FALSE, mycountry=NULL)
```


## Plot posterior point estimates

```{r, include=TRUE, message=FALSE, eval=FALSE}
plot_subnational_point_estimates(main_path = "results/subnational/global_nonspatial/", pkg_data = pkg_data, vis_path = "visualisations/subnational/global_nonspatial", local=FALSE, mycountry=NULL)
```
